BookStore/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using BookStore.Context;
using BookStore.Models;
using BookStore.Utils;
using PagedList;

namespace BookStore.Controllers
{
    public class AdminController : Controller
    {
        protected BookStoreContext dbContext = BookStoreContext.GetInstance();

        private static int PAGE_SIZE = 6;
        public ActionResult Index(int? page)
        {
            if (SessionHelper.IsUserLoggedIn(Session) && SessionHelper.GetUser(Session).UserType == UserType.ADMIN)
            {
                var viewModel = new AdminViewModel();
                viewModel.Books = dbContext.Books.ToList().ToPagedList((page == null || page < 1) ? 1 : (int)page, PAGE_SIZE);
                if (viewModel.Books == null)
                {
                    viewModel.Books = new List<Book>().ToPagedList((page == null || page < 1) ? 1 : (int)page, PAGE_SIZE);
                }
                return View(viewModel);
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(int? page, string context)
        {
            if (SessionHelper.IsUserLoggedIn(Session) && SessionHelper.GetUser(Session).UserType == UserType.ADMIN)
            {
                var viewModel = new AdminViewModel();
                viewModel.Books = dbContext.Books.ToList().ToPagedList((page == null || page < 1) ? 1 : (int)page, PAGE_SIZE);
                if (viewModel.Books == null)
                {
                    viewModel.Books = new List<Book>().ToPagedList((page == null || page < 1) ? 1 : (int)page, PAGE_SIZE);
                }
                if (context != null)
                {
                    viewModel.Books = viewModel.Books
                        .ToList()
                        .Where( bk => 
                            bk.Name.Contains(context) ||
                            bk.Description.Contains(context) ||
                            bk.Author.Contains(context)
                        )
                        .ToList()
                        .ToPagedList(page ?? 1, PAGE_SIZE);
                }
                return View(viewModel);
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        public ActionResult CreateBook()
        {
            if (SessionHelper.IsUserLoggedInAndAdmin(Session))
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateBook([Bind(Include = "Id,Name,Author,Description,Cost")] Book book)
        {
            if (SessionHelper.IsUserLoggedInAndAdmin(Session))
            {
                if (ModelState.IsValid)
                {
                    dbContext.Books.Add(book);
                    await dbContext.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                return View(book);
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditBook([Bind(Include = "Id,Name,Description,Author,Cost")] Book book)
        {
            if (SessionHelper.IsUserLoggedInAndAdmin(Session))
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        public async Task<ActionResult> DeleteBook(long? bookId)
        {
            if (SessionHelper.IsUserLoggedInAndAdmin(Session))
            {
                var book = await dbContext.Books.FindAsync(bookId);
                if (book == null)
                {
                    return RedirectToAction("NoSuchBook", "Error", new { id = bookId });
                }
                return View(book);
            }
            return RedirectToAction("Login", "User");
        }

        [HttpPost, ActionName("DeleteBook")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long? id)
        {
            if (SessionHelper.IsUserLoggedInAndAdmin(Session))
            {
                var book = await dbContext.Books.FindAsync(id);
                dbContext.Books.Remove(book);
                await dbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Login", "User");
        }
    }
}

BookStore/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Context;
using BookStore.Utils;

namespace BookStore.Controllers
{
    public class MainController : Controller
    {
        protected BookStoreContext dbContext = BookStoreContext.GetInstance();
        public ActionResult Index()
        {
            var user = SessionHelper.GetUser(Session);
            if (user != null)
            {
                var books = dbContext.Books.ToList();
                var viewModel = new Models.BooksViewModel();
                viewModel.Books = books;
                viewModel.AmountInRow = 2;
                return View(viewModel);
            }
            return RedirectToAction("Login", "User");
        }

        public ActionResult About()
        {
            if (SessionHelper.IsUserLoggedInAndAdmin(Session))
            {

                ViewBag.Message = "This website was created as course project for WEB-technologies discipline.";

                return View();
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        public ActionResult Contact()
        {
            if (SessionHelper.IsUserLoggedInAndAdmin(Session))
            {

                ViewBag.Message = "Contact page.";

                return View();
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }
    }
}

BookStore/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BookStore", "Index", "Main", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Main")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (BookStore.Utils.SessionHelper.GetUser(Session) == null)
                    {
                        <li>@Html.ActionLink("Login", "Login", "User", new { area = "" }, new { @class = "navbar-brand" })</li>
                    }
                    else
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">@BookStore.Utils.SessionHelper.GetUser(Session).Login<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Logout", "Logout", "User")</li>
                                @if (BookStore.Utils.SessionHelper.GetUser(Session).UserType == BookStore.Models.UserType.ADMIN)
                                {
                                    <li>@Html.ActionLink("Manage books", "Index", "Admin")</li>
                                }
                            </ul>
                        </li>
                    }
                </ul>

                @using (Html.BeginForm("Index", "Admin", FormMethod.Post, new { @class="navbar-form navbar-right", role="search"}))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <input type="text" class="form-control" name="context" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                }
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr/>
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - BookStore</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BookStore/Views/Shared/_Layout.cshtml
@using BookStore.Utils;
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BookStore", "Index", "Main", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Main")</li>
                    <li>@Html.ActionLink("Информация", "About", "Main")</li>
                    <li>@Html.ActionLink("Связаться", "Contact", "Main")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (BookStore.Utils.SessionHelper.GetUser(Session) == null)
                    {
                        <li>@Html.ActionLink("Login", "Login", "User", new { area = "" }, new { @class = "navbar-brand" })</li>
                    }
                    else
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">@BookStore.Utils.SessionHelper.GetUser(Session).Login<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Logout", "Logout", "User")</li>
                                @if (SessionHelper.GetUser(Session).UserType == BookStore.Models.UserType.ADMIN)
                                {
                                    <li>@Html.ActionLink("Manage books", "Index", "Admin")</li>
                                }
                            </ul>
                        </li>
                    }
                </ul>

                @if (SessionHelper.IsUserLoggedIn(Session))
                {
                    <ul class="nav nav-pills navbar-right">
                        <li class="active"><a href="@Url.Action("Index", "Cart")">Cart <span class="badge">@SessionHelper.GetCart(Session).GetTotalAmount()</span></a></li>
                    </ul>
                }
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="text-center">&copy; @DateTime.Now.Year - BookStore</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>